### ISSUE TITLE
Flash CS5.5

### ISSUE THREAD

**Issue by AyazSardar** [fljot/GestouchExamples#1]
Hi,

How can i use Gestouch in Flash CS5.5?

Please advice.

Regards,

Ayaz

**Comment by fljot** [comment]
Just as any other library: add the sources or compiled swc to the classpath.
for example http://active.tutsplus.com/tutorials/workflow/how-to-use-an-external-library-in-your-flash-projects/

If you're asking how to compile this examples with Flex CS — you can't. This is a Flex project (used here just to quickly build the interface). But you don't need any specific IDE to run it as the build process is powered by Ant. All you need is Flex SDK and Ant to build this up.
