### ISSUE TITLE
external stats really need?

### ISSUE THREAD

**Issue by boozook** [fljot/GestouchExamples#3]
I talk about src_external / fr / kouma / starling / utils / Stats.as

Starling have it now:
see https://github.com/PrimaryFeather/Starling-Framework/blob/master/starling/src/starling/core/Starling.as#L625

**Comment by fljot** [comment]
Not really an issue =)) but I'll drop them once update to latest Starling swc

**Comment by boozook** [comment]
OK :) Close this issue.

**Comment by fljot** [comment]
Ты лучше по теме давай) Что неудобно, что непонятно (после внимательного просмотра яббловских видео и примеров), что лучше может сделать...

**Comment by boozook** [comment]
В жаббере не отвечаешь. По теме: с адапторами и рефлексией очень тяжело разобрался - всё вроде логично, а вот на ошибки нарывался. Давай в джаббере.

**Comment by fljot** [comment]
Каком ещё джаббере... я сегодня в магазине wifi включил в инет залезть посмотреть отзывы про наушники, а там от тебя что-то в gtalk вылезло. Я хз что это (какая-то приблуда gmail-овская судя по всему + целое приложение в андроиде).
У меня скайп, и ты это знаешь =)

**Comment by boozook** [comment]
1. gtalk = джаббер
2. Skype я не шибко жалую и ты это знаешь :)

**Comment by fljot** [comment]
Это ж браузер надо держать открытым...
